<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Export Division</name>
   <tag></tag>
   <elementGuidId>3c926173-def8-4f1a-99e7-9d0808f99f54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='smoothmenu1']/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>723f0086-9f14-44ad-9878-9bbbfdac9973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.nsden.com/export-division.htm</value>
      <webElementGuid>58ac3455-e050-4b22-ab82-2798ec688dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Export Division</value>
      <webElementGuid>230e14a9-837b-4cfc-a378-46c3cdfed0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>55b082db-8ae0-446a-b87c-f637f9b634d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Export Division</value>
      <webElementGuid>ace75b31-c64e-4885-a701-0ca7d1374945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;smoothmenu1&quot;)/ul[1]/li[3]/a[@class=&quot;selected&quot;]</value>
      <webElementGuid>dfefafa3-20b3-4e0c-89ea-3a370ff2fc7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='smoothmenu1']/ul/li[3]/a</value>
      <webElementGuid>005c7cb5-e8dc-463d-a6fd-286fa9e0bc50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Export Division')]</value>
      <webElementGuid>9d378612-88c7-49f8-8bf3-ac11ece9f209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/following::a[1]</value>
      <webElementGuid>012df473-b9e5-4c5f-a92f-40bf76ed4348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>197eb653-eac7-4c23-b795-8e4fa74c85a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fresh Vegetables'])[1]/preceding::a[1]</value>
      <webElementGuid>aebf8c49-9966-4bba-b336-0c5b2a6f3bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fresh Fruits'])[1]/preceding::a[2]</value>
      <webElementGuid>40f6ddb6-ab4a-4476-8297-b52ffdf60acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Export Division']/parent::*</value>
      <webElementGuid>63038a46-7a5d-4f48-b442-6a3df024a7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.nsden.com/export-division.htm']</value>
      <webElementGuid>b74c6319-3f05-4a9e-b26b-87e7f424c00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/ul/li[3]/a</value>
      <webElementGuid>56b319cd-2435-4953-86eb-49a47393e06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.nsden.com/export-division.htm' and @title = 'Export Division' and (text() = 'Export Division' or . = 'Export Division')]</value>
      <webElementGuid>fe4a3b9c-276c-4d79-8a3a-f798a543ca5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
