<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Industrial Division</name>
   <tag></tag>
   <elementGuidId>b79e805f-ca31-4dcd-97fa-d69ac3e3fa48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='smoothmenu1']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb99f394-5928-4295-b5bb-508bf74df090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.nsden.com/industrial-division.htm</value>
      <webElementGuid>55f06f9b-9869-4333-b59f-3b7e0098f029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Industrial Division</value>
      <webElementGuid>f8f720ce-b930-4b00-8a06-f9cc1b7e970c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>15699958-7637-4c92-a6c7-41d4aee99f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Industrial Division</value>
      <webElementGuid>521d4430-628b-463e-b71a-7c4cbaf83565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;smoothmenu1&quot;)/ul[1]/li[4]/a[@class=&quot;selected&quot;]</value>
      <webElementGuid>42d78176-a9c9-4351-88d4-83d6864e492a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='smoothmenu1']/ul/li[4]/a</value>
      <webElementGuid>9b610e64-6b2f-4f88-b436-9458eb5465cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Industrial Division')]</value>
      <webElementGuid>94a7d761-f8ff-4936-8f7d-13436e1f2280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leather Products'])[1]/following::a[1]</value>
      <webElementGuid>5c320ad7-3f41-466c-ac5f-fec1edc7cb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Animal feed'])[1]/following::a[2]</value>
      <webElementGuid>67807128-cde1-4d0b-997f-47bb18953cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fluid Handling Accessories'])[1]/preceding::a[1]</value>
      <webElementGuid>279bb490-94b5-413a-876e-d0e6c7ed7f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paint Spray Gun'])[1]/preceding::a[2]</value>
      <webElementGuid>e4abfbf3-78ee-479a-9d5f-28e6b87c3b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Industrial Division']/parent::*</value>
      <webElementGuid>b097004a-238d-40e2-8084-251db903f021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.nsden.com/industrial-division.htm']</value>
      <webElementGuid>009ed275-d15d-4d8c-958c-dfb57b455a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/ul/li[4]/a</value>
      <webElementGuid>5d3a48f5-fdc9-4f6b-8a9c-5144f3802b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.nsden.com/industrial-division.htm' and @title = 'Industrial Division' and (text() = 'Industrial Division' or . = 'Industrial Division')]</value>
      <webElementGuid>a310e71b-8143-4ffe-bc7f-9381b87ba58a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
