<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Concrete Methods</name>
   <tag></tag>
   <elementGuidId>e11fbd20-3ed2-4889-a1a2-f45c4448f7e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#t4 > span > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='t4']/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>39d22094-3c9a-4ac5-a6c7-17f64e5577e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:show(8);</value>
      <webElementGuid>24ef1c91-4a7b-4042-bd03-87880bb16b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Concrete Methods</value>
      <webElementGuid>7b1c3900-9872-4e67-9791-5a99362e579f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t4&quot;)/span[1]/a[1]</value>
      <webElementGuid>84072f95-e30a-44c7-9e1c-6928599a9999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BiDiProvider/iframe_classFrame</value>
      <webElementGuid>04315381-4240-453b-adf2-88b1170929cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='t4']/span/a</value>
      <webElementGuid>626f70a1-f994-4a79-8c3f-59fcf2b9176b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Concrete Methods')]</value>
      <webElementGuid>763fb69a-633b-4d44-92f1-a4c5e71ecd2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instance Methods'])[1]/following::a[1]</value>
      <webElementGuid>293005f9-e3c0-4660-ab71-99518a762e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Methods'])[1]/following::a[2]</value>
      <webElementGuid>39cea8c6-5c27-46d0-a518-35af545cf149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modifier and Type'])[1]/preceding::a[1]</value>
      <webElementGuid>94b004b8-1d79-418c-8ac4-a20c2bae57dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Method'])[3]/preceding::a[1]</value>
      <webElementGuid>48c5af19-52ea-456c-abb9-8f9924fdf662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Concrete Methods']/parent::*</value>
      <webElementGuid>e5f2e0c1-575b-4a99-a28d-5874b4391cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:show(8);')]</value>
      <webElementGuid>211a72d4-0edc-434d-94ed-6e7b77784804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span/a</value>
      <webElementGuid>b8d45d5c-b601-4b2d-a927-4d8b61579db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:show(8);' and (text() = 'Concrete Methods' or . = 'Concrete Methods')]</value>
      <webElementGuid>a0497765-3251-4742-9324-a14857ebb669</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
