<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Certificates</name>
   <tag></tag>
   <elementGuidId>4778a031-518f-41f0-9cfb-7adf6f0fa8eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Certificates&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='smoothmenu1']/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>13a729df-a157-476f-a39d-6747ffac1804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.nsden.com/certificates.htm</value>
      <webElementGuid>9ad67c30-154f-4c3a-9c07-55e5682304ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Certificates</value>
      <webElementGuid>47ec7352-f06a-4752-bb24-838392db63e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Certificates</value>
      <webElementGuid>a25630db-70e7-426e-ba6a-bb0eae8989d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;smoothmenu1&quot;)/ul[1]/li[5]/a[1]</value>
      <webElementGuid>3758107a-9670-4058-ac46-1dbd3ff649f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='smoothmenu1']/ul/li[5]/a</value>
      <webElementGuid>8705ca06-2ce5-425c-a425-567c9a36a73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Certificates')]</value>
      <webElementGuid>f07a2626-85f8-426c-a743-dbe4efc8894f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='customized machine'])[1]/following::a[1]</value>
      <webElementGuid>f05eb501-c442-4983-8583-20e5a57a032a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Industrial Automation'])[1]/following::a[2]</value>
      <webElementGuid>a93f0463-246b-4700-9a4f-02f07a5f3d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::a[2]</value>
      <webElementGuid>81770a16-1809-420a-995e-d05892a21e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[2]/preceding::a[3]</value>
      <webElementGuid>dd5d1c13-e0fc-42fd-b151-0d7fdd38ab34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Certificates']/parent::*</value>
      <webElementGuid>0cfc272a-3ef7-4c46-8026-df15458f053c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.nsden.com/certificates.htm']</value>
      <webElementGuid>234b56a8-69f6-4830-9efd-973cd8aeae11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>120148f7-5a8e-4ced-a192-aa96433929ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.nsden.com/certificates.htm' and @title = 'Certificates' and (text() = 'Certificates' or . = 'Certificates')]</value>
      <webElementGuid>879514de-4678-44be-96f4-f2c594ffee79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
