<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AbstractHttpCommandCodec.CommandSpec</name>
   <tag></tag>
   <elementGuidId>8626fc59-2fa8-4363-a42c-efd78b9e5bc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AbstractHttpCommandCodec.CommandSpec')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e935ea46-237c-4a69-a35a-64516be3510c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/remote/codec/AbstractHttpCommandCodec.CommandSpec.html</value>
      <webElementGuid>6df24d14-7ab8-452b-9029-4bec4c5cbb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.remote.codec</value>
      <webElementGuid>c57c9a64-f00f-43df-a3b3-a1da8634c87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>38eadebd-354e-4e8a-8f9d-90be0142560a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AbstractHttpCommandCodec.CommandSpec</value>
      <webElementGuid>3b93df4b-ebfa-4ebc-9ca6-78d365f62e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;indexContainer&quot;]/ul[1]/li[5]/a[1]</value>
      <webElementGuid>b92559bd-6859-4fe2-83c6-c36fe57db859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Overview/iframe_packageFrame</value>
      <webElementGuid>f657e88c-058f-4673-8ef3-9425f4e0685d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AbstractHttpCommandCodec.CommandSpec')]</value>
      <webElementGuid>42419ba3-7cb8-4487-b96d-38182887a25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractHttpCommandCodec'])[1]/following::a[1]</value>
      <webElementGuid>b1180a3c-ba94-4488-903f-89b07e3c6508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractFindByBuilder'])[1]/following::a[2]</value>
      <webElementGuid>d5128446-a896-4058-9689-790b8069e45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractHttpResponseCodec'])[1]/preceding::a[1]</value>
      <webElementGuid>c289c9f9-4fc1-4cae-b4d2-cb0c1221242b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractWebDriverEventListener'])[1]/preceding::a[2]</value>
      <webElementGuid>08d87873-610e-4784-86ba-47f76ad40891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AbstractHttpCommandCodec.CommandSpec']/parent::*</value>
      <webElementGuid>37aa45b5-688f-40d7-9908-1258d9be7a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/remote/codec/AbstractHttpCommandCodec.CommandSpec.html')]</value>
      <webElementGuid>f39c303b-981f-4313-a4af-2c19a4337373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>56954323-4f7b-4ee1-8012-8181a1db3599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/remote/codec/AbstractHttpCommandCodec.CommandSpec.html' and @title = 'class in org.openqa.selenium.remote.codec' and (text() = 'AbstractHttpCommandCodec.CommandSpec' or . = 'AbstractHttpCommandCodec.CommandSpec')]</value>
      <webElementGuid>03f7494a-4b24-4864-a896-7e99933d9e99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
