<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Calories  0-50</name>
   <tag></tag>
   <elementGuidId>34d8771c-8755-42e1-9081-5381143e1577</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bodyFormatNT']/div/div/ul/li[3]/div/div/div[3]/div[2]/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b2d664c5-a628-4f89-8903-f0937e02a110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt10px</value>
      <webElementGuid>9a41e709-d319-4056-8734-8084cca90869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calories : 0-50</value>
      <webElementGuid>bd99cbd4-2ced-48a4-a25b-10958aebea20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyFormatNT&quot;)/div[@class=&quot;scale-animation bdrEffect&quot;]/div[@class=&quot;cf_4img-flex ac-mb30px fullImageFrame&quot;]/ul[@class=&quot;lsn m0px p0px fo idv_eqheight ac-al&quot;]/li[@class=&quot;ac&quot;]/div[@class=&quot;pr ofh lh0 cp data&quot;]/div[@class=&quot;dib ofh&quot;]/div[@class=&quot;left-slide-box pa ac lh15em&quot;]/div[@class=&quot;mt5px lh14em al&quot;]/p[@class=&quot;mt10px&quot;]</value>
      <webElementGuid>d45b3226-0653-4e62-bfb5-a5edd9ddc1df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyFormatNT']/div/div/ul/li[3]/div/div/div[3]/div[2]/p[2]</value>
      <webElementGuid>769153a1-7b0d-42bf-ba12-a97b8e172aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHOLESTROL :'])[1]/following::p[1]</value>
      <webElementGuid>41eb65c2-c615-441a-ac47-b6091b9b0282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processed Food'])[3]/following::p[2]</value>
      <webElementGuid>ff51bcd2-a647-4a61-89e5-4e86e5e2ccbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carbohydrates :'])[1]/preceding::p[1]</value>
      <webElementGuid>e40e718b-375d-4dd7-9729-6731b0182a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0-50']/parent::*</value>
      <webElementGuid>2842520c-bacc-4d6a-8fcc-4607f2819bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div[3]/div[2]/p[2]</value>
      <webElementGuid>c0795fb8-40a2-4bee-8583-52a59ffeadee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Calories : 0-50' or . = 'Calories : 0-50')]</value>
      <webElementGuid>ddac2fb1-2c79-46bc-9026-005d4613b348</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
