<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BiDiProvider</name>
   <tag></tag>
   <elementGuidId>dae4491e-a04b-4905-bada-18dca32abbe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'BiDiProvider')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>28a7c67a-c9d8-424a-86ff-3e6edbfbfb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>BiDiProvider.html</value>
      <webElementGuid>80e58b3b-02b8-4a81-8abc-a026675738df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.bidi</value>
      <webElementGuid>07717573-fb84-411b-b71b-5d43ad4b4ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>070a57c9-fd62-4073-ae5a-1ebebfa1e11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BiDiProvider</value>
      <webElementGuid>99dd78be-6b79-43a9-bf61-b53ba79e1f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;indexContainer&quot;]/section[2]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>192fc86b-d826-4dec-9081-6ae9a57e2f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_AbstractHttpCommandCodec.CommandSpec/iframe_packageFrame</value>
      <webElementGuid>fae631c3-0bf0-49b7-a2f5-0acc6eaf9888</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BiDiProvider')]</value>
      <webElementGuid>4a5b864d-26a0-4313-8dc6-33c3c440768e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BiDi'])[1]/following::a[1]</value>
      <webElementGuid>52497287-eea1-4fde-99d3-eb694c224c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classes'])[1]/following::a[2]</value>
      <webElementGuid>cdd02a8c-4bf5-45a4-b2a9-e1b259a0cd02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BiDiSessionStatus'])[1]/preceding::a[1]</value>
      <webElementGuid>bc4e748f-762e-4dd2-a560-83f150290064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Command'])[1]/preceding::a[2]</value>
      <webElementGuid>e147e56a-df20-4da3-a372-e4aefbbc4015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BiDiProvider']/parent::*</value>
      <webElementGuid>97089fb1-9351-48ed-bdc5-f68fce518f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'BiDiProvider.html')]</value>
      <webElementGuid>36d7e804-91ce-47af-91d1-90ef4e648f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>5ae2a5ec-b81b-4052-bf78-1bb9f42682c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'BiDiProvider.html' and @title = 'class in org.openqa.selenium.bidi' and (text() = 'BiDiProvider' or . = 'BiDiProvider')]</value>
      <webElementGuid>9f0188ad-fd5a-47b0-924d-6f279dec3789</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
